spring:
  security:
    user:
      name: admin
      password: password
    # 配置开启csrf保护，关闭csrf保护请设置为false
    # 开启csrf保护后需要在前端请求中添加CSRF token
    csrf:
      enabled: true
    # 配置不需要进行权限验证的url
    # 多个url使用逗号分隔
    ignore:
      - /health
      - /info
    # 配置拦截的url及其所需要的权限
    # 多个url使用逗号分隔，多个权限使用空格分隔
    # /admin/** 需要 ADMIN 权限，/user/** 需要 USER 权限
    # /public/** 不需要权限即可访问
    # 注意：这里需要按照权限高低顺序进行配置，例如 /admin/** 需要 ADMIN 权限，/admin/user/** 需要 USER 权限
    authorizeRequests:
      - /admin/** ADMIN
      - /user/** USER
      - /public/**
