spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mlib?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
  mail:
    host: smtp.163.com
    username: lmiomail@163.com
    password: VPNNRWHYFWJHSRPN
    port: 465
    properties:
      form: lmiomail@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.lmio.mlib.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl